///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/checkbox.h>
#include <wx/dialog.h>
#include <wx/gdicmn.h>
#include <wx/radiobut.h>
#include <wx/spinctrl.h>

class PublicationDialogBase : public wxDialog
{
public:
    PublicationDialogBase() {}
    PublicationDialogBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Publication",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Publication",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr);

    enum
    {
        ID_CHK_A = wxID_HIGHEST + 1,
        ID_CHK_ALL,
        ID_CHK_B,
        ID_CHK_BEST_EFFORT,
        ID_CHK_BLUE,
        ID_CHK_C,
        ID_CHK_CIRCLE,
        ID_CHK_CYAN,
        ID_CHK_D,
        ID_CHK_GREEN,
        ID_CHK_MAGENTA,
        ID_CHK_ORANGE,
        ID_CHK_PURPLE,
        ID_CHK_RED,
        ID_CHK_RELIABLE,
        ID_CHK_SQUARE,
        ID_CHK_TRIANGLE,
        ID_CHK_YELLOW
    };

protected:

    // Class member variables

    wxCheckBox* m_checkBox;
    wxCheckBox* m_checkBox_2;
    wxCheckBox* m_checkBox_3;
    wxCheckBox* m_checkBox_4;
    wxCheckBox* m_checkBox_5;
    wxRadioButton* m_radioBlue;
    wxRadioButton* m_radioBtn;
    wxRadioButton* m_radioBtn_2;
    wxRadioButton* m_radioCircle;
    wxRadioButton* m_radioCyan;
    wxRadioButton* m_radioGreen;
    wxRadioButton* m_radioMagenta;
    wxRadioButton* m_radioOrange;
    wxRadioButton* m_radioPurple;
    wxRadioButton* m_radioRed;
    wxRadioButton* m_radioSquare;
    wxRadioButton* m_radioTriangle;
    wxRadioButton* m_radioYellow;
    wxSpinCtrl* m_spinSize;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
