///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <wx/sizer.h>

#include "ReaderSampleListDialogBase.h"

bool ReaderSampleListDialogBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto* dlg_sizer = new wxBoxSizer(wxVERTICAL);

    m_dataViewCtrl = new wxDataViewCtrl(this, ID_DATAVIEW);
    dlg_sizer->Add(m_dataViewCtrl, wxSizerFlags(1).Expand().Border(wxALL));

    m_dataViewColumn = m_dataViewCtrl->AppendTextColumn("Color", 0, wxDATAVIEW_CELL_INERT, -1,
        static_cast<wxAlignment>(wxALIGN_LEFT), wxDATAVIEW_COL_RESIZABLE);

    m_dataViewColumn_2 = m_dataViewCtrl->AppendTextColumn("ShapeSize", 1, wxDATAVIEW_CELL_INERT, -1,
        static_cast<wxAlignment>(wxALIGN_LEFT), wxDATAVIEW_COL_RESIZABLE);

    m_dataViewColumn_3 = m_dataViewCtrl->AppendTextColumn("X", 2, wxDATAVIEW_CELL_INERT, -1,
        static_cast<wxAlignment>(wxALIGN_LEFT), wxDATAVIEW_COL_RESIZABLE);

    m_dataViewColumn_4 = m_dataViewCtrl->AppendTextColumn("Y", 3, wxDATAVIEW_CELL_INERT, -1,
        static_cast<wxAlignment>(wxALIGN_LEFT), wxDATAVIEW_COL_RESIZABLE);

    SetSizer(dlg_sizer);
    SetMinSize(ConvertDialogToPixels(wxSize(240, 240)));
    Fit();
    Centre(wxBOTH);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
