///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/dataview.h>
#include <wx/dialog.h>
#include <wx/gdicmn.h>

class ReaderSampleListDialogBase : public wxDialog
{
public:
    ReaderSampleListDialogBase() {}
    ReaderSampleListDialogBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title =
        wxEmptyString, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString,
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr);

    enum
    {
        ID_DATAVIEW = wxID_HIGHEST + 1
    };

protected:

    // Class member variables

    wxDataViewColumn* m_dataViewColumn;
    wxDataViewColumn* m_dataViewColumn_2;
    wxDataViewColumn* m_dataViewColumn_3;
    wxDataViewColumn* m_dataViewColumn_4;
    wxDataViewColumn* m_dataViewColumn_5;
    wxDataViewCtrl* m_dataViewCtrl;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
