///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/checkbox.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>
#include <wx/panel.h>
#include <wx/statusbr.h>
#include <wx/toolbar.h>

class CanvasPanel;

class ShapesDemoFrameBase : public wxFrame
{
public:
    ShapesDemoFrameBase() {}
    ShapesDemoFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString,
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(300, 300),
        long style = wxDEFAULT_FRAME_STYLE, const wxString &name = wxFrameNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString,
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(300, 300),
        long style = wxDEFAULT_FRAME_STYLE, const wxString &name = wxFrameNameStr);

    enum
    {
        ID_CANVAS = wxID_HIGHEST + 1,
        ID_PUBLISH,
        ID_SUBSCRIBE
    };

protected:

    // Class member variables

    CanvasPanel* m_panel;
    wxCheckBox* m_checkBox;
    wxStatusBar* m_statusBar;
    wxToolBar* m_toolBar;
};

namespace wxue_img
{
    // Images declared in this class module:

    extern const unsigned char pub_svg[257];
    extern const unsigned char sub_svg[258];
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
